// AUTO-GENERATED by tools/setup_country.dart
// ⚠️  Do NOT edit manually. Run:  dart tools/setup_country.dart
//
// Current: 🇮🇳  India
//   Phone dial code : +91
//   Phone ISO       : IN
//   Currency symbol : ₹
//   Currency code   : INR

// ignore_for_file: constant_identifier_names

import 'country_config.dart';

/// The default country compiled into this build.
/// Change it by running:  dart tools/setup_country.dart
const CountryCode kDefaultCountry = CountryCode.india;

/// App Version name extracted from pubspec.yaml
const String kAppVersion = '1.4.4';
